apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fsainovich/flask-deploy.git
    targetRevision: HEAD # or a specific branch/tag like 'main' or 'v1.0.0'
    path: 
  destination:
    server: https://kubernetes.default.svc # Or your cluster's API server URL
    namespace: flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
